InternetStore/Models/Product.cs
using System;

namespace InternetStore.Models;
public class Product
{
    public string Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Size { get; set; }

    public string Image { get; set; }

    public int Price { get; set; }

    public int Rate { get; set; }

    public Category Category { get; set; }

    public Product()
    {
        Id = Guid.NewGuid().ToString();
    }
}

InternetStore/Components/CategoriesListViewComponent.cs
using InternetStore.Domain;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using System.Threading.Tasks;

namespace InternetStore.Components
{
    public class CategoriesListViewComponent : ViewComponent
    {
        private readonly IMongoCollection<Category> _categories;
        public CategoriesListViewComponent(IMongoDatabase database)
        {
            _categories = database.GetCollection<Category>("Categories");
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await _categories.Find(item => true).ToListAsync();
            return View(items);
        }
    }
}

InternetStore/Components/ProductQuantityViewComponent.cs
using InternetStore.Domain;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using MongoDB.Driver;
using System.Linq;
using Microsoft.AspNetCore.Http;
using InternetStore.Infrastructure;

namespace InternetStore.Components
{
    public class ProductQuantityViewComponent : ViewComponent
    {
        private readonly IMongoCollection<Cart> _carts;
        public ProductQuantityViewComponent(IMongoDatabase database)
        {
            _carts = database.GetCollection<Cart>("Carts");
        }   

        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.Get<Cart>("Cart");

            if (cart == null)
            {
                var email = UserClaimsPrincipal.FindFirstValue(ClaimTypes.Email);
                cart = _carts.Find(items => items.User.Email == email).FirstOrDefault();
                HttpContext.Session.Set("Cart", cart);
            }

            var quantity = cart?.Products.Select(item => item.Quantity).Sum();

            return View(quantity);
        }
    }
}

InternetStore/Views/Shared/_CartProduct.cshtml
@using InternetStore.Models;
@model ProductCart

<li class="cart_item item_list d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-lg-end justify-content-start">
    <div class="product d-flex flex-lg-row flex-column align-items-lg-center align-items-start justify-content-start mr-auto">
        <div>
            <div class="product_number"></div>
        </div>
        <div>
            <div class="product_image"><img src="@Model.Image" alt=""></div>
        </div>
        <div class="product_name_container">
            <div class="product_name"><a href="#">@Model.Title</a></div>
        </div>
    </div>
    <div class="product_size product_text"><span>Size: </span>@Model.Size</div>
    <div class="product_price product_text"><span>Price: </span>$@Model.Price</div>
    <div class="product_quantity_container">
        <div class="product_quantity">
            <button class="buttons_quantity">+</button>
            <span class="product_text product_num">@Model.Quantity</span>
            <button class="buttons_quantity">-</button>
        </div>
    </div>
    <div class="product_total product_text"><span>Total: </span>$@Multiply(@Model.Price,@Model.Quantity)</div>
</li>

@functions{
    public int Multiply(int x, int y) => x * y;
}

InternetStore/Views/Shared/_Layout.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Esala</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Little Closet template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    @RenderSection("Links",required:false)

</head>
<body>

    <div class="super_container">

        <!-- Header -->

        <header class="header">
            <div class="header_overlay"></div>
            <div class="header_content d-flex flex-row align-items-center justify-content-start">
                <div class="logo">
                    <a href="/">
                        <div class="d-flex flex-row align-items-center justify-content-start">
                            <div><img src="/images/logo_1.png"></div>
                            <div>Esala</div>
                        </div>
                    </a>
                </div>
                <nav class="main_nav">
                    <ul class="d-flex flex-row align-items-start justify-content-start">
                        @await Component.InvokeAsync("CategoriesList")
                    </ul>
                </nav>
                <div class="header_right d-flex flex-row align-items-center justify-content-start ml-auto">
                    <!-- User -->
                    <div class="products_dropdown user_dropdown_sorting">
                        <div class="user">
                            <div><img src="~/images/user.svg" alt=""></div>
                        </div>
                        <ul>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a href="#">@User.Identity.Name</a></li>
                                <li><a asp-action="SignOut" asp-controller="UserAccount">Sign Out</a></li>
                            }
                            else
                            {
                                <li><a asp-action="SignIn" asp-controller="UserAccount">Sign In</a></li>
                                <li><a asp-action="SignUp" asp-controller="UserAccount">Sign Up</a></li>
                            }
                        </ul>
                    </div>
                    <!-- Cart -->
                    <div class="cart" style="display:flex;">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a asp-action="Cart" asp-controller="Cart">
                                <div>
                                    <img class="svg" src="~/images/cart.svg" alt="">
                                </div>

                            </a>
                            @await Component.InvokeAsync("ProductQuantity")
                        }
                        else
                        {
                            <a asp-action="SignIn" asp-controller="UserAccount">
                                <div><img class="svg" src="~/images/cart.svg" alt=""></div>
                            </a>
                        }
                    </div>
                    <!-- Phone -->
                    <div class="header_phone d-flex flex-row align-items-center justify-content-start">
                        <div><div><img src="~/images/phone.svg" alt=""></div></div>
                        <div>MY_TELEPHONE</div>
                    </div>
                </div>
            </div>
        </header>

        <div class="super_container_inner">
            <div class="super_overlay"></div>

            @RenderBody()

        </div>

        @*        <footer>
        <div class="navbar navbar-dark navbar-expand-md bg-dark">
        <div class="navbar-nav ml-auto">
        <a class="nav-item nav-link" href="http://www.facebook.com">
        <i class="fab fa-facebook-f fa-2x"></i>
        </a>
        <a class="nav-item nav-link" href="http://www.vk.com">
        <i class="fab fa-vk fa-2x"></i>
        </a>
        <a class="nav-item nav-link" href="http://www.twitter.com">
        <i class="fab fa-twitter fa-2x"></i>
        </a>
        </div>
        </div>
        </footer>*@

    </div>

    @RenderSection("Scripts",required:false)

</body>
</html>

InternetStore/Views/Shared/_Product.cshtml
@using InternetStore.Domain;
@model Product

<div class="product">
    <div class="product_image">
        <a asp-controller="Home" asp-action="Product" asp-route-id="@Model.Id">
            <img src="@Model.Image" alt="">
        </a>
    </div>
    <div class="product_content">
        <div class="product_info d-flex flex-row align-items-start justify-content-start">
            <div>
                <div>
                    <div class="product_name">
                        <a asp-controller="Home" asp-action="Product" asp-route-id="@Model.Id">@Model.Title</a>
                    </div>
                    <div class="product_category">In Category</div>
                </div>
            </div>
            <div class="ml-auto text-right">
                <div class="rating_r rating_r_4 home_item_rating">
                    @for (int i = 0; i < Model.Rate; i++)
                    {
                        <i></i>
                    }
                </div>
                <div class="product_price text-right">$@Model.Price</div>
            </div>
        </div>
        <div class="product_buttons">
            <div class="text-right d-flex flex-row align-items-start justify-content-start">
                <div class="product_button product_fav text-center d-flex flex-column align-items-center justify-content-center">
                    <div>
                        <div>
                            <img src="~/images/heart_2.svg" class="svg" alt="">

                        </div>
                    </div>
                </div>

                <div class="product_button product_cart text-center d-flex flex-column align-items-center justify-content-center">
                    <div>

                        <div>
                            <a asp-controller="Home" asp-action="Product" asp-route-id="@Model.Id">
                                <img src="~/images/cart.svg">
                            </a>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

InternetStore/Views/Shared/_Slide.cshtml
@using InternetStore.Domain;
@model Product


<div class="owl-item">
    <div class="background_image" style="background-image:url(/images/back.jpg)"></div>
    <div class="container fill_height">
        <div class="row fill_height">
            <div class="col fill_height">
                <div class="home_container d-flex flex-column align-items-center justify-content-start">
                    <div class="home_content">
                        <div class="home_title">New Collections</div>
                        <div class="home_subtitle">Summer Wear</div>
                        <div class="home_items">
                            <div class="row">
                                <div class="col-sm-3 offset-lg-1">
                                    <div class="home_item_side">
                                        <a href="product.html">
                                            <img src="/images/home_1.jpg" alt="">
                                        </a>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 col-sm-8 offset-sm-2 offset-md-0">
                                    <div class="home_item_large">

                                        <div class="product_image">
                                            <a href="#"><img src="@Model.Image" alt=""></a>
                                        </div>

                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="home_item_side">
                                        <a href="product.html">
                                            <img src="/images/home_3.jpg" alt="">
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>